### ISSUE TITLE
Creation milestones Gitlab Terraform provider

### ISSUE THREAD

**Issue by terraform-gitlab-modules** [terraform-gitlab-modules/terraform-gitlab-microservices-bumper#4]

**Comment by terraform-gitlab-modules** [comment]
https://github.com/gitlabhq/terraform-provider-gitlab/

**Comment by Moon1706** [comment]
PR - https://github.com/gitlabhq/terraform-provider-gitlab/pull/1044

**Comment by Moon1706** [comment]
https://github.com/gitlabhq/terraform-provider-gitlab/pull/1044#pullrequestreview-980800036
